# Generated by Django 5.0.4 on 2024-04-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
