# Generated by Django 5.0.4 on 2024-04-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0022_product_sku_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disscount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2),
        ),
    ]
