# Generated by Django 5.0.4 on 2024-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0023_product_disscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='disscount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
