# Generated by Django 5.0.4 on 2024-04-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0024_alter_product_disscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='disscount',
            new_name='disscount_per',
        ),
    ]
