# Generated by Django 5.0.4 on 2024-04-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0027_alter_coupon_product_alter_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
