# Generated by Django 5.0.4 on 2024-04-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0028_coupon_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='product',
        ),
    ]
