# Generated by Django 5.0.4 on 2024-04-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0029_remove_coupon_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='vaild',
            new_name='vaild_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
