# Generated by Django 5.0.4 on 2024-04-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0033_alter_useraddress_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='mobile_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
