# Generated by Django 5.0.4 on 2024-04-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0035_useraddress_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
